/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { isMobile } from 'react-device-detect'

export function Caixa(props) {
  const { nodes, materials } = useGLTF('/ChefNaCaixa.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0.422, 2.074, 0.543]} rotation={[.7, 0, 0]} scale={isMobile ? 2 : 3}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={materials['Material.001']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cube003_1.geometry}
          material={materials.chefmetallic}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/ChefNaCaixa.glb')